### ISSUE TITLE
Too many small cassandra partitions result in overmuch spark partitions

### ISSUE THREAD

**Issue by posa88** [datastax/spark-cassandra-connector#1049]
I have a user table with primary key:(id, time), so there will be lots of partition in cassandra.
It seems spark create a spark partition for each cassandra partition, Is there a way to tune it down without changing the table?

**Comment by bcantoni** [comment]
@posa88 please raise this question on the [mailing list](https://github.com/datastax/spark-cassandra-connector#mailing-list) instead. We are no longer using GitHub Issues.
