### ISSUE TITLE
CassandraRunner.scala:71: value isAlive is not a member of Process

### ISSUE THREAD

**Issue by miludedeng** [datastax/spark-cassandra-connector#1067]
[error] /Users/steven/Documents/software/spark-2.0.2-bin-hadoop2.7/spark-cassandra-connector/spark-cassandra-connector-embedded/src/main/scala/com/datastax/spark/connector/embedded/CassandraRunner.scala:71: value isAlive is not a member of Process
[error]   if (!waitForPortOpen(InetAddress.getByName(baseConfiguration.rpcAddress), baseConfiguration.nativeTransportPort, 100000, () => !process.isAlive)) {

I got this error when i execute the command “sbt/sbt assembly”. I do not kown  how to fix it.

**Comment by RussellSpitzer** [comment]
You are using Java 7 and need to be using Java 8
