### ISSUE TITLE
spark.cassandra.* properties with camelcases not working when setting as option to sqlContext.read

### ISSUE THREAD

**Issue by markush81** [datastax/spark-cassandra-connector#1094]
When setting some options not directly via SparkContext, but as option to sqlContext.read and they are camelCased the whole thing fails, cause of `org.apache.spark.sql.execution.datasources.DataSource#resolveRelation` which transforms all options to `val caseInsensitiveOptions = new CaseInsensitiveMap(options)`.

    object SparkCassandraConnector extends App {

      val spark = SparkSession.builder
        .appName("Spark Cassandra Connector Sample")
        .config("spark.cassandra.connection.host", "localhost")
        .getOrCreate()

      private val sqlContext = spark.sqlContext

      import org.apache.spark.sql.cassandra._

      private val dataFrame = sqlContext
        .read
        .cassandraFormat("wordcount", "sample")
        .option("spark.cassandra.output.ifNotExists", "true")
        .load()

      dataFrame.show(10)
    }

fails with

    Exception in thread "main" com.datastax.spark.connector.util.ConfigCheck$ConnectorConfigurationException: Invalid Config Variables
    Only known spark.cassandra.* variables are allowed when using the Spark Cassandra Connector. 
    spark.cassandra.output.ifnotexists is not a valid Spark Cassandra Connector variable.
    Possible matches:
    spark.cassandra.output.ifNotExists
        at com.datastax.spark.connector.util.ConfigCheck$.checkConfig(ConfigCheck.scala:51)
        at com.datastax.spark.connector.cql.CassandraConnectorConf$.apply(CassandraConnectorConf.scala:249)
        at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:257)
        at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:56)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:330)`

So in case you need to set specifically here (this example maybe no, but if you use multiple cassandra connections and have to use SSL) and can't set in SparkSession.build.config or directly in spark.conf this is a real stopper.

I am not sure wether this is a Spark Bug or a spark-cassandra-connector bug in its origin. But since Spark does that for all read formats, maybe more likely a connector issue, also interestingly the DataFrameWriter `save` does this caseInsensistiveOptions thing only in case of `case format: FileFormat 
        val caseInsensitiveOptions = new CaseInsensitiveMap(options)`.

In case of `load` all the time

     def resolveRelation(checkPathExist: Boolean = true): BaseRelation = {
         val caseInsensitiveOptions = new CaseInsensitiveMap(options)

**Comment by RussellSpitzer** [comment]
I noticed this, but we don't use github issues, can you please make a jira for tracking? I've noticed that Spark just auto lowercases all options :man_shrugging:

**Comment by markush81** [comment]
Done https://datastax-oss.atlassian.net/projects/SPARKC/issues/SPARKC-479.

**Comment by rayqiu** [comment]
Just a note - camel cased parameters worked fine with 2.0.0-M3 release.

**Comment by RussellSpitzer** [comment]
@rayqiu did they work when passed as options to a dataframe? I'm having a hard time imagining how they would have :/

**Comment by rayqiu** [comment]
yes, there was no error when passing it to a DataFrame to write to file

**Comment by RussellSpitzer** [comment]
So my repo is different

```scala
case class KVRow (k: Int, v: Int)
import org.apache.spark.sql.SaveMode
val ds = spark.createDataset(Seq(KVRow(1,2)))
ds.write.format("org.apache.spark.sql.cassandra").options(Map("table" -> "kv", "keyspace" -> "ks", "spark.cassandra.output.ifNotExists" -> "true")).mode(SaveMode.Append).save()
```
Works on 2.0.0-M3, 2.0.0-RC1, and 2.0.0

BUT on Reading

```scala
spark.read.format("org.apache.spark.sql.cassandra").options(Map("table" -> "kv", "keyspace" -> "ks", "spark.cassandra.output.ifNotExists" -> "true")).load()
```
Fails on
2.0.0, 2.0.0-RC1, but not M3

So for a workaround you can make sure you don't pass the option to the Read portion. I'll be working on a global fix and closing this issue. Please put all future comments on the JIRA
https://datastax-oss.atlassian.net/projects/SPARKC/issues/SPARKC-479
