### ISSUE TITLE
Tuple schema discrepancy with Dataframes

### ISSUE THREAD

**Issue by erikschlegel** [datastax/spark-cassandra-connector#1133]
Running into some issues when working with Tuples and Dataframes. Constructing a Dataset with a tuple of `conjunctiontopics: (Option[String], Option[String], Option[String])`  for my case class. The C* schema is `conjunctiontopics frozen<tuple<text, text, text>>,`. The Dataset schema inferred from the cassandra table is different from the dataset. When I run `newDS1.printSchema` I see 
```
 |-- conjunctiontopics: struct (nullable = true)
 |    |-- _1: string (nullable = true)
 |    |-- _2: string (nullable = true)
 |    |-- _3: string (nullable = true)
```

The upstream cassandra table returns 
``` 
|-- conjunctiontopics: struct (nullable = true)
 |    |-- 0: string (nullable = true)
 |    |-- 1: string (nullable = true)
 |    |-- 2: string (nullable = true)
```

This results in the following error when I attempt to run a join on both datasets. 
``` Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve '(`conjunctiontopics` = `conjunctiontopics`)' due to data type mismatch: differing types in '(`conjunctiontopics` = `conjunctiontopics`)' (struct<_1:string,_2:string,_3:string> and struct<0:string,1:string,2:string>).;;
'Project [pipelinekey#143, placeid#147, periodtype#141, period#142, externalsourceid#139, conjunctiontopics#150, periodstartdate#138L, periodenddate#140L, mentioncount#144, avgpossentiment#145, avgnegsentiment#146, centroidlat#148, centroidlon#149, mentioncount#84L, periodstartdate#85, periodenddate#86, centroidlat#87, centroidlon#88, avgnegsentiment#89, avgpossentiment#90, insertiontime#91] ```

**Comment by bcantoni** [comment]
This project is no longer using GitHub issues; instead please use JIRA:
https://github.com/datastax/spark-cassandra-connector#reporting-bugs
