### ISSUE TITLE
Support of spark-cassandra-connector Apache Spark 2.2.0 and Apache Cassandra 3.1.1

### ISSUE THREAD

**Issue by kaushalshriyan** [datastax/spark-cassandra-connector#1134]
Any timelines regarding support of spark-cassandra-connector for Apache Spark 2.2.0 and Apache Cassandra 3.1.1?

**Comment by RussellSpitzer** [comment]
It is currently supported.

**Comment by bcantoni** [comment]
This project is no longer using GitHub issues; instead please use JIRA:
https://github.com/datastax/spark-cassandra-connector#reporting-bugs
