### ISSUE TITLE
Support Structured Streaming

### ISSUE THREAD

**Issue by alonl** [datastax/spark-cassandra-connector#1150]
Hi guys,
Any intentions to support Spark Structured Streaming API? I couldn't find any issue.
Thanks!

**Comment by leoromanovsky** [comment]
FYI - https://github.com/datastax/spark-cassandra-connector/issues/546

**Comment by alonl** [comment]
Sorry. I recommend adding this notification to the Issue template :)

**Comment by alonl** [comment]
Recreated here:
https://datastax-oss.atlassian.net/browse/SPARKC-510

**Comment by leoromanovsky** [comment]
I don’t maintain this project just happen to notice your issue as I was browsing.
