### ISSUE TITLE
Support for Cassandra java driver versions 3.2 or higher?

### ISSUE THREAD

**Issue by ngenuity** [datastax/spark-cassandra-connector#1152]
Is there going to be a new version of the spark connector released soon that will include the Cassandra Java driver version 3.2 or higher?  I would like to use the Object Mapping features that seem to only be in version 3.2+.  If not, is it recommended to exclude the java-driver from the spark connector and including the latest java driver or are they not compatible?

**Comment by RussellSpitzer** [comment]
There is an unshaded artifact for placing new java drivers in the connector as noted in the FAQ. 
https://github.com/datastax/spark-cassandra-connector/blob/master/doc/FAQ.md#how-do-i-use-libraries-which-depend-on-the-cassandra-java-driver

I will probably bump the driver version in the next release though.
