### ISSUE TITLE
Is any performance benchmark available for spark Cassandra connector? 

### ISSUE THREAD

**Issue by sparkcassuser** [datastax/spark-cassandra-connector#1177]
I use NYC taxi data set of approx. 30 million rows with 5 GB storage. I use sparklyr and crassy package to read/write data from/to spark cassandra. The experiments are performed on a  cluster of 4 nodes (8 cores, 16GB RAM each); and spark cassandra are collocated on each node. I got read latency 4.032 seconds to read data from cassandra to spark as dataframe. Then I add two more columns to dataframe and then write back to cassandra. I got write latency 7176.550 seconds. Why i got too fast read and too slow write? I have used all spark cassandra connect parameters with default values. even if i changed the config$spark.cassandra.input.split.size_in_mb, it gives me the almost same read latency.

are these results fine? Is there any benchmark available to compare my results?

**Comment by bcantoni** [comment]
@sparkcassuser we are no longer using GitHub Issues on this project. See this link for various ways to contact other community users:
https://github.com/datastax/spark-cassandra-connector#community
