### ISSUE TITLE
pushdown

### ISSUE THREAD

**Issue by znxzjx** [datastax/spark-cassandra-connector#1178]
日志中不显示 pushdown 标志“Scan org.apache.spark.sql.cassandra.CassandraSourceRelation@2493eec6 [user#0,word#1,count#2] ReadSchema: struct<user:string,word:string,count:int>
”

**Comment by bcantoni** [comment]
@znxzjx we are no longer using GitHub Issues on this project. See this link for various ways to contact other community users:
https://github.com/datastax/spark-cassandra-connector#community
