### ISSUE TITLE
Filtering on cassandra side using joinWithCassandraTable

### ISSUE THREAD

**Issue by dkota1992** [datastax/spark-cassandra-connector#1186]
I have been trying to do a join operation applying a pushdown filter. The primary key for cassandra table is `(source_id, parent_id, id)`.

    `val joinedVal = sourceValues.joinWithCassandraTable(db_name, table_name, SomeColumns("col1", "col2")).on(SomeColumns("source_id", "parent_id"))`

Source values is a RDD of SourceValue that is coming from kafka source. This is a **Streaming Job**
    `SourceValue(source_id: String, parent_id: String, start: String, end: String)`

Now what I want to achieve is to do a where condition on the joinedVal, where the id should be within the range of start and end of sourceValues.

Where condition works for a static value just by applying `.where("id > ?", "staticValue")` , but I want it to be from the left value (start and end) instead of being static.

Other way of getting around this problem is to do a filter operation 
`joinedVal.filter(value => value._2.get[String]("id") > value._1.start && value._2.get[String]("id") < value._1.end)`
which ends up reading the whole table and then doing filter operation on the spark side instead of on the Cassandra side.

**Comment by RussellSpitzer** [comment]
#546
