### ISSUE TITLE
implicit conversion doesn't work with spark cassandra connector

### ISSUE THREAD

**Issue by git4sun** [datastax/spark-cassandra-connector#1192]
I use datastax cassandra java driver in a scala project. And I use an implicit method to convert ResultSetFuture to Future[ResultSet] in scala. Here's the code:

    implicit def listenableFutureToFuture[T](listenableFuture: ListenableFuture[T]): Future[T] = {
    val promise = Promise[T]()
    Futures.addCallback(listenableFuture, new FutureCallback[T] {
      def onFailure(error: Throwable): Unit = {
        promise.failure(error)
        ()
      }

      def onSuccess(result: T): Unit = {
        promise.success(result)
        ()
      }
    })
    promise.future
    } 

This works fine. I can access cassandra and get the Future[ResultSet]. But when I add `"com.datastax.spark" %% "spark-cassandra-connector" % "2.3.1"` to my project, it failed to build. Throw error:

    Error:(33, 25) type mismatch;
     found   : com.datastax.driver.core.ResultSetFuture
     required: scala.concurrent.Future[com.datastax.driver.core.ResultSet]
        session.executeAsync(q)

I checked the dependency jars for hours and finally ruled out all other libraries. It is the spark-cassandra-connector library that cause the implicit stop working. I don't know what's going on here. Any help?

**Comment by RussellSpitzer** [comment]
#546
