### ISSUE TITLE
Please let me know dose the data stored in dataframe direcitly, when it is pulled from cassandra

### ISSUE THREAD

**Issue by Kumarswapnil** [datastax/spark-cassandra-connector#1193]
I am using below code :- 
dataframe = spark.read\
    	    .format("org.apache.spark.sql.cassandra")\
    	    .options(table="****", keyspace="****")\
    	    .load().show()

**Comment by bcantoni** [comment]
@Kumarswapnil we are no longer using GitHub Issues on this project. See this link for various ways to contact other community users and/or report bugs:
https://github.com/datastax/spark-cassandra-connector#community
