### ISSUE TITLE
Cassandra Table count retrieves different values when running with multiple executors.

### ISSUE THREAD

**Issue by mariusneo** [datastax/spark-cassandra-connector#1195]
```
sparkSession.sparkContext
      .cassandraTable[SearchEventByUser]("my_keyspace","my_table")
      .count
```

When running the statement above on a single machine I get always the same number (2073831).

Running the job with multiple machines in the spark cluster, retrieves a kind of approximate value of the number of entries in the table (2070976) with is always a bit different.

I tried the same program with both of the version 2.0.6 and 2.0.9 of the connector and got similar (inconsistent) results.

Is the number of the entries of a table actually an approximation linked to spark-cassandra-connector?

**Comment by bcantoni** [comment]
@mariusneo we are no longer using GitHub Issues on this project. See this link for various ways to contact other community users and/or report bugs:
https://github.com/datastax/spark-cassandra-connector#community
