### ISSUE TITLE
Camel Case issue still persistent in 2.0.6 even though it says resolved in 2.0.0

### ISSUE THREAD

**Issue by niravns** [datastax/spark-cassandra-connector#1215]
com.datastax.spark.connector.util.ConfigCheck$ConnectorConfigurationException: Invalid Config Variables Only known spark.cassandra.* variables are allowed when using the Spark Cassandra Connector. spark.cassandra.splitcount is not a valid Spark Cassandra Connector variable. Possible matches: spark.cassandra.input.split.size_in_mb at com.datastax.spark.connector.util.ConfigCheck$.checkConfig(ConfigCheck.scala:51) at com.datastax.spark.connector.cql.CassandraConnectorConf$.apply(CassandraConnectorConf.scala:251) at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:268) at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:56) at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:306) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146) at DataFrameFromTo.cassandraToDataFrame(DataFrameFromTo.scala:382) at Migration.jsonSourceDestinationToDataFrame(Migration.scala:386) at Migration$$anonfun$migrate$2.apply(Migration.scala:118) at Migration$$anonfun$migrate$2.apply(Migration.scala:111) at scala.collection.immutable.Range.foreach(Range.scala:160) at Migration.migrate(Migration.scala:111) at DataMigrationFramework$$anonfun$main$3$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(DataMigrationFramework.scala:353) at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) at DataMigrationFramework$$anonfun$main$3.apply$mcV$sp(DataMigrationFramework.scala:351) at scala.util.control.Breaks.breakable(Breaks.scala:38) at DataMigrationFramework$.main(DataMigrationFramework.scala:350) at DataMigrationFramework.main(DataMigrationFramework.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:635)

**Comment by niravns** [comment]
This says its resolved https://datastax-oss.atlassian.net/browse/SPARKC-479 but its not resolved in 2.0.6

**Comment by RussellSpitzer** [comment]
The parameter you are using doesn't exist in 2.0.6
https://github.com/datastax/spark-cassandra-connector/commit/499eced1f301a57ee884463251d391281b725b64

Also please send questions to the mailing list, the github issues are not checked.
