### ISSUE TITLE
How to Generate TimeUuid in PySpark?

### ISSUE THREAD

**Issue by guzelcihad** [datastax/spark-cassandra-connector#1217]
Hi,
I want to learn how to generate TimeUuid in Pyspark. I couldn't find a solution in Python.
Thanks

**Comment by RussellSpitzer** [comment]
You would have to use the PythonDriver if you need a utility for that. http://datastax.github.io/python-driver/api/cassandra/util.html

But the Spark only allows for String types to be used as UUIDs so you would still need to convert to strings before using with the SCC.

Also please direct questions to the Mailing List. Github issues are not checked.
