### ISSUE TITLE
Does spark-cassandra-connector support built-in load balanceing?

### ISSUE THREAD

**Issue by MJ-DEV91** [datastax/spark-cassandra-connector#1222]
Hello.
Does spark-cassandra-connector support built-in load balanceing? Is there any documentations in this regard?
As datastax says, only DSE derivers support built-in load balancing.
My project is Scala based and I want to use Scala-based driver for connectiong to Cassandra, but this built-in load balancing is really important to me.
Is it possible to use built-in load balancing using spark-cassandra-connector?

**Comment by RussellSpitzer** [comment]
As I replied on the mailing list yes, for more details please check out
https://groups.google.com/a/lists.datastax.com/forum/#!topic/spark-connector-user/SO5LNOToPKU
