### ISSUE TITLE
Spark-Cassandra-Connector Metrics

### ISSUE THREAD

**Issue by polyzos** [datastax/spark-cassandra-connector#1224]
Hi I'm trying to find a way to collect the metrics exposed from the connector. 
After some a little investigation i managed to collect the metrics in csv files with the example `metrics.properties` file i found on the source code. 
What i see is that the metrics file will be generated only after the job finishes and in general i would prefer to collect them in something like prometheus or elastic.
Can you please suggest alternatives on how to collect the exposed metrics?

**Comment by RussellSpitzer** [comment]
Please use the mailing list for questions, metrics can be enabled please see the doc section on metrics and will be processed through Spark's metric system which allows a variety of sinks.

https://spark.apache.org/docs/latest/monitoring.html#metrics (statsD or graphite will probably be what you want)
