### ISSUE TITLE
spark kafka data not getting inserted into cassandra table

### ISSUE THREAD

**Issue by johnpalantir** [datastax/spark-cassandra-connector#1225]
Hi 
While writing data to cassandra from spark-streaming, data is not getting written. The flash back is:
I am doing a kafka-sparkStreaming-cassandra integration.
I am reading kafka messages and trying to put it in a cassandra table CREATE TABLE users ( id UUID PRIMARY KEY, userfirstname text, userlastname text);
kafka to spark-streaming is running cool, but spark to cassandra, there is some issue...data not getting written to table.
I am able to create a connection with cassandra, but the data is not getting inserted into the cassandra table.

JDK 11 Spark <dependency>
    <groupId>org.apache.spark</groupId>
    <artifactId>spark-core_2.12</artifactId>
    <version>2.4.4</version>  2.2.1<
</dependency>

import com.datastax.spark.connector.japi.CassandraJavaUtil;
import com.palantir.model.User;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.function.*;
import org.apache.spark.streaming.Durations;
import org.apache.spark.streaming.api.java.JavaDStream;
import org.apache.spark.streaming.api.java.JavaInputDStream;
import org.apache.spark.streaming.api.java.JavaStreamingContext;
import org.apache.spark.streaming.kafka010.ConsumerStrategies;
import org.apache.spark.streaming.kafka010.KafkaUtils;
import org.apache.spark.streaming.kafka010.LocationStrategies;

import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import java.io.Serializable;
import java.util.*;

public class SparkKafkaCassandra implements Serializable {
    
    public static void main(String[] argv) throws Exception {

        System.setProperty("hadoop.home.dir", "/");

        String keySpaceName = "test";
        String tableName = "users";

        JSONParser parser = new JSONParser();
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);

        // Configure Spark to connect to Kafka running on local machine
        Map<String, Object> kafkaParams = new HashMap<>();
        kafkaParams.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        kafkaParams.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG,
                "org.apache.kafka.common.serialization.StringDeserializer");
        kafkaParams.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG,
                "org.apache.kafka.common.serialization.StringDeserializer");
        kafkaParams.put(ConsumerConfig.GROUP_ID_CONFIG, "group2");
        kafkaParams.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");
        kafkaParams.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, true);

        // Configure Spark to listen messages in topic test
        Collection<String> topics = Arrays.asList("test10");

        SparkConf conf = new SparkConf().setMaster("local[2]").setAppName("KafkaCassandra");

        conf.set("spark.cassandra.connection.host", "127.0.0.1");
        conf.set("spark.cassandra.connection.port", "9042");
        conf.set("spark.cassandra.connection.timeout_ms", "5000");
        conf.set("spark.cassandra.read.timeout_ms", "200000");

        // Creating spark context
        JavaSparkContext javaSparkContext = new JavaSparkContext(conf);

        // Creating Straming context by using spark context. Read messages in batch of 30 seconds
        JavaStreamingContext jssc = new JavaStreamingContext(javaSparkContext, Durations.seconds(5));

        // Start reading messages from Kafka and get DStream
        final JavaInputDStream<ConsumerRecord<String, String>> stream = KafkaUtils.createDirectStream(jssc,
                LocationStrategies.PreferConsistent(),
                ConsumerStrategies.<String, String> Subscribe(topics, kafkaParams));

        // Read value of each message from Kafka and return it
        JavaDStream<String> lines = stream.map(new Function<ConsumerRecord<String, String>, String>() {

            @Override
            public String call(ConsumerRecord<String, String> kafkaRecord) throws Exception {
                return kafkaRecord.value();
            }
        });

        // Read each message and cast to object.
        lines.foreachRDD((VoidFunction<JavaRDD<String>>) rdd -> {

            if (rdd.count() != 0) {

                JSONObject jsonObj = (JSONObject) parser.parse(rdd.first());
                User userObj = mapper.readValue(jsonObj.toString(), User.class);
                userObj.setId(UUID.randomUUID());
                List<User> list = new ArrayList<>();
                list.add(userObj);
                JavaRDD<User> userRDD = javaSparkContext.parallelize(list);

                System.out.println(userRDD.first());
                // Save into cassandra
                CassandraJavaUtil.javaFunctions(userRDD)
                        .writerBuilder(keySpaceName, tableName, CassandraJavaUtil.mapToRow(User.class))
                        .saveToCassandra();

                System.out.println("end");
            }

        });

        jssc.start();
        jssc.awaitTermination();

    }

Error Details:

23:25:05.667 [main] DEBUG org.apache.spark.SparkContext - Adding shutdown hook
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at com.datastax.spark.connector.util.ConfigParameter.<init>(ConfigParameter.scala:7)
	at com.datastax.spark.connector.writer.WriteConf$.<init>(WriteConf.scala:60)
	at com.datastax.spark.connector.writer.WriteConf$.<clinit>(WriteConf.scala)
	at com.datastax.spark.connector.BatchSize$.<init>(BatchSize.scala:14)
	at com.datastax.spark.connector.BatchSize$.<clinit>(BatchSize.scala)
	at com.datastax.spark.connector.japi.CassandraJavaUtil.<clinit>(CassandraJavaUtil.java:1664)
	at com.palantir.test.CassandraSparkTest.main(CassandraSparkTest.java:52)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 7 more

**Comment by RussellSpitzer** [comment]
This looks like a Scala Version error, a mismatch of scala versions on the runtime classpath and those on the compiled classpath, please check our [FAQ](https://github.com/datastax/spark-cassandra-connector/blob/master/doc/FAQ.md#why-am-i-seeing-scala-version-mismatch-error) for more info.

My guess is you used a 2.11 SCC and are using 2.12 Spark?
