### ISSUE TITLE
Support 'chaining' Cassandra RDDs

### ISSUE THREAD

**Issue by davidtinker** [datastax/spark-cassandra-connector#175]
We need to be able to chain Cassandra operations together. The first operation finds the ids of the rows needed by the next operation. Something like this:

```sql
CREATE TABLE word_index (
  word text,
  item_id text,
  PRIMARY KEY (word, item_id)
);

CREATE TABLE items (
  id text,
  description: text,
  PRIMARY KEY (id)
);
```

```groovy
def words = ["dog", "cat", "pig"]
def word_index = javaFunctions(sc).cassandraTable("ks", "word_index")
def items = javaFunctions(sc).cassandraTable("ks", "items")

JavaRDD<String> ids = word_index.select("item_id")
    .where("word in ?", words)
    .map({CassandraRow row -> row.getString(0) })
    .distinct()

JavaRDD<String> descriptions = items.select("description")
    .where("id in ?", ids)
    .map({CassandraRow row -> row.getString(0) })
```

There could be very many words and ids so the RDDs need to have multiple partitions + thats why I can't just use a Java collection for the ids.

Is there another way to do this sort of thing in Spark?

**Comment by jacek-lewandowski** [comment]
The related tickets are now in JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC-3
https://datastax-oss.atlassian.net/browse/SPARKC-25

**Comment by jacek-lewandowski** [comment]
We are sorry, but we are going to disable GitHub tracker. 

If you have problems and you are looking for help, please use a forum at: https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If you want to report bugs, improvement or feature requests, please use JIRA at:
https://datastax-oss.atlassian.net/browse/

Please move your questions to the new location.

Thanks
