### ISSUE TITLE
quick start guide - be more explicit

### ISSUE THREAD

**Issue by rustyrazorblade** [datastax/spark-cassandra-connector#177]
The quick start guide also seems to have a prerequisite that you already know what this means:

```
Configure a new Scala project with the following dependencies:

Apache Spark 0.9 or 1.0 and its dependencies
Apache Cassandra thrift and clientutil libraries matching the version of Cassandra
DataStax Cassandra driver for your Cassandra version
```

I have no idea what to do with this, and since most people aren't familiar with Scala, I suspect it's a significant hurdle to getting started.

Is it possible to either expand on this instruction or to at least link to the appropriate documentation?

**Comment by jacek-lewandowski** [comment]
Moved to JIRA: https://datastax-oss.atlassian.net/browse/SPARKC-48
