### ISSUE TITLE
Add CassandraInputDStream

### ISSUE THREAD

**Issue by helena** [datastax/spark-cassandra-connector#284]
val stream: ReceiverInputDStream[T] =
   CassandraUtils.createStream[T](ssc, rdd, storageLevel)

**Comment by fr0stbyte** [comment]
Really interested in this one -- any chance this gets merged in soon ?

**Comment by jacek-lewandowski** [comment]
Moved to Jira: https://datastax-oss.atlassian.net/browse/SPARKC-40
