### ISSUE TITLE
Streaming support for Apache Flume  

### ISSUE THREAD

**Issue by tanejagagan** [datastax/spark-cassandra-connector#297]

**Comment by jacek-lewandowski** [comment]
We are sorry, but we are going to disable GitHub tracker. 

If you have problems and you are looking for help, please use a forum at: https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If you want to report bugs, improvement or feature requests, please use JIRA at:
https://datastax-oss.atlassian.net/browse/

Please move your questions to the new location.

Thanks
