### ISSUE TITLE
Add Listeners for Job Status and Anomalies with Logging

### ISSUE THREAD

**Issue by helena** [datastax/spark-cassandra-connector#314]
For example: https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/JobListener.scala

**Comment by jacek-lewandowski** [comment]
I think we can make it a part of https://datastax-oss.atlassian.net/browse/SPARKC-27. WDYT @helena ? If so, please add a link to this PR in SPARKC-27 and close this PR.

**Comment by helena** [comment]
Moving ticket.
