### ISSUE TITLE
Issues Inserting Collections (List) into Cassandra using Mulesoft driver 1.2.2

### ISSUE THREAD

**Issue by challakk** [datastax/spark-cassandra-connector#349]
I was trying to insert records into Cassandra using "Execute cql query" operation for CassandraDB connector (ver 1.2.2). The query is made up of ints and strings, with the last 4 fields being Collection type List. 

If I test by inserting the exact same query directly into cqlsh or DataStax Dev Center (and add a trailing semicolon), the insert works fine. But if I try it from within a Mule flow, I get the following error: 

org.mule.api.MessagingException: Failed to invoke executeCqlQuery. 
 com.mulesoft.mule.cassandradb.CassandraDBException 
 InvalidRequestException(why:line 1:1056 no viable alternative at character ']') 

Can someone help me with the resolution. Thanks

**Comment by bcantoni** [comment]
Closing this older discussion because we are going to turn off GitHub Issues soon.

If there are follow-up comments or help needed, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
