### ISSUE TITLE
[Info Req] When is data refreshed from Cassandra?

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#353]
Imagine this scenario:

I've a Streaming job. Before start, I read `rddMasterData = sc.cassandraTable("master", "data")`. 
Then on each iteration of the streaming job, I join `rddMasterData` with the streamed data. After applying some filter function to the resulting stream, I insert additional data on the table backing up  `rddMasterData`.

Will the new data in the Cassandra table `master.data` be loaded on `rddMasterData` the next iteration?

I've done some manual tests on a shell session + cqlsh inserts side by side and found out that the RDD is reloaded but not always. Following the Spark principles, a given RDD will be recreated when it's used on an operation and it's not available in memory anymore.  I'm wondering whether this behavior is tunable for the CassandraRDD.

The opposite behavior is controllable: That is, if I mark `rddMasterData` as cached, it will never be reloaded again from the source cassandra table.

Would you have the loading semantics of the CassandraRDD documented somewhere? (or at least some guidelines on what behavior we can count on) ?

kr, Gerard.

**Comment by bcantoni** [comment]
Closing because it looks like this discussion has concluded.

If there are follow-up comments, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
