### ISSUE TITLE
Add version compatibility matrix to the Readme

### ISSUE THREAD

**Issue by bcantoni** [datastax/spark-cassandra-connector#390]
It would be helpful to have a version compatibility table in the readme that explains which version of this connector goes with Spark, Cassandra, etc.

For example:

| connector | spark | cassandra |
| --- | --- | --- |
| 1.1 | 1.0, 1.1 | 2.0, 2.1 |
| 1.0 | 0.9, 1.0 | 2.0 |

**Comment by helena** [comment]
+1
