### ISSUE TITLE
Better documentation on driver partitioning policy

### ISSUE THREAD

**Issue by hymanroth** [datastax/spark-cassandra-connector#402]
I have spent many hours reading the issues here and have also studied the driver source code (not easy if you don't know Scala very well) but there are still many questions which are left unanswered.

For example:

1. What happens when RF = N?
If all the nodes have all the data, how does the driver spread out the query across the cluster? How does it decide which node loads which subset of the query data?

2. What happens when a node has no data?
What happens when a node does not have any local data (either because its token range is not required or because its rows are filtered server side)? Does it simply load an empty RDD? 

3. What happens if you specify the partition key in a where clause? 
With RF=1 this means only one node has the entire row. What do the other nodes load? At the other extreme, with RF=N, all the nodes have the row so we're back to question 1.

This is just a sample, I've got many more questions.

I suggest you add a page to the documentation section explaining in detail how such decisions are made.

This will allow developers to optimize around these decisions instead of (at least in my case) trawling through numerous log files and Cassandra traces trying to work out what's actually going on.

Thanks.

**Comment by bcantoni** [comment]
Closing because it looks like this discussion has concluded.

If there are follow-up comments, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
