### ISSUE TITLE
read timeout for query with token range and secondary index together

### ISSUE THREAD

**Issue by ashira11** [datastax/spark-cassandra-connector#418]
read timeout for query with token range and secondary index together

I create below table with cassandra 2.0.9

CREATE TABLE basic_logitem (
  logid timeuuid,
  body text,
  ymd int,
  PRIMARY KEY ((logid))
);
CREATE INDEX basic_logitem_ymd_idx ON basic_logitem (ymd);

and execute read query by this

session.execute("SELECT logid, body, ymd FROM irionlog.basic_logitem WHERE token(logid) > 323098120938102983 AND token(logid) <= 523098120938102983 AND ymd = 20141104 ALLOW FILTERING");

and I found read timeout exception.

but that query with cqlsh was OK.

below 2 query was OK, too.
session.execute("SELECT logid, body, ymd FROM irionlog.basic_logitem WHERE ymd = 20141104 ALLOW FILTERING");
session.execute("SELECT logid, body, ymd FROM irionlog.basic_logitem WHERE token(logid) > 323098120938102983 AND token(logid) <= 523098120938102983 ALLOW FILTERING");

any solution for this?

**Comment by bcantoni** [comment]
Closing because it looks like this discussion has concluded.

If there are follow-up comments, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
