### ISSUE TITLE
Spark SQL Thrift JDBC server

### ISSUE THREAD

**Issue by mohammedguller** [datastax/spark-cassandra-connector#437]
Hi - Are there any plans to provide integration between Spark SQL Thrift JDBC server and Cassandra? 

Thanks,
Mohammed

**Comment by bcantoni** [comment]
Closing because it looks like this discussion has concluded.

If there are follow-up comments, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

**Comment by rpiotti** [comment]
Is there another issue to track the enhancement request for a Spark SQL Thrift JDBC server and Cassandra?
