### ISSUE TITLE
Performance Monitoring

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#439]
Hi,

I would like to know what would be the recommended practices to monitor performance of jobs interacting with Cassandra through this driver? Are there metrics being published in the Spark metrics subsystem?
I've a Streaming job that's giving me a performance headache and I'm currently in the dark with regards to insertion performance to Cassandra.

Thanks,
Gerard.

**Comment by maasg** [comment]
@jacek-lewandowski For the record, I'm now running a count before an insert to avoid writes of 0-sized RDDs. Looks like the cost of count is less than the cost of the empty write and therefore positive for my time-budget.

**Comment by jacek-lewandowski** [comment]
@maasg the related issue has been created in [JIRA](https://datastax-oss.atlassian.net/browse/SPARKC-27) and will be implemented for Connector 1.2.

**Comment by maasg** [comment]
cool! thanks.
