### ISSUE TITLE
No host Available unless all nodes 

### ISSUE THREAD

**Issue by ashic** [datastax/spark-cassandra-connector#450]
I've got a spark stand alone cluster with 4 nodes and a Spark master. The 4 worker nodes also have apache cassandra 2.1.1 running on them. I'm using the Spark Cassandra Connector version 1.1.0.

If I have sparkConf.set("spark.cassandra.connection.host", "Host1,Host2,Host3,Host4") then everything seems to work fine. However, if I specify

sparkConf.set("spark.cassandra.connection.host", "Host1,Host2")

then I get a " All host(s) tried for query failed (no host was tried)" error and jobs are failing.

Here, Host1 and Host2 are the seeds for cassandra. Each node has the following setting in Cassandra.yaml:

rpc_address: ip_address_of_node
broadcast_address: ip_address_of_node

Host1..4 are not ip addresses, but hostnames. Pinging on each box suggests dns is working fine. Also, connecting from C# applications and Dev Center with Host1,2 as seeds seems to work fine.

Is there a setting I'm missing, or could this be a bug?

Note: I'm setting the local_dc setting as well:

System.setProperty("spark.cassandra.connection.local_dc", "prod1")

**Comment by bcantoni** [comment]
Closing because we are moving away from GitHub Issues.

For any follow-ups, please raise in the users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
