### ISSUE TITLE
No schema agreement from live replicas after 10000 ms.

### ISSUE THREAD

**Issue by xuzhongxing** [datastax/spark-cassandra-connector#451]
This is a question for help, not a issue of the connector itself.

I have a keyspace with 2 replicas. In my driver program, I created a table with

```
session.execute("create table ....")
```

And I save to the table immediately with rdd.saveToCassandra()
In spark log I see error message:
```
No schema agreement from live replicas after 10000 ms. The schema may not be up to date on some nodes.
```

I know that it is due to the latency of the seed node propagating the table creation to all nodes. I solve this problem by a hack of waiting for 15 seconds after creating the table. Is there a better or "correct" way to do it?

**Comment by xuzhongxing** [comment]
No, ours is not a permanent error. It's just because that the newly created table meta information has not been propagated to all nodes. So it could be solved by waiting some time, like 15 seconds. But I feel this solution is too adhoc.

**Comment by bcantoni** [comment]
This is something you can encounter on a multi-node Cassandra cluster when you do inserts immediately after creating or altering a table. It's not elegant, but the most common solution is to wait N seconds for the schema to replicate to all nodes prior to doing any writes.

I'll close this issue. For any follow-ups, let's move to the user's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
