### ISSUE TITLE
Caching of cluster information in Spark Streaming

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#465]
Hi there!

On my spark streaming job, I see for each micro-batch and each executor that the cassandra cluster topology is fetched from the ring.
This is taking 2-3 secs on each iteration and when I'm on a budget of 10s, it's really expensive.

Could this topology be cached? Or is there some tuning option I can change to adapt the behavior of the connector?

A sample log:

```bash
14/12/08 18:55:18 DEBUG com.datastax.spark.connector.cql.CassandraConnector: Attempting to open native connection to Cassandra at {xx.xx.xx.138}:9042
14/12/08 18:55:20 INFO com.datastax.spark.connector.cql.LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.136 (datacenter1)
14/12/08 18:55:20 INFO com.datastax.spark.connector.cql.LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.135 (datacenter1)
14/12/08 18:55:20 INFO com.datastax.spark.connector.cql.LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.137 (datacenter1)
14/12/08 18:55:20 INFO com.datastax.spark.connector.cql.LocalNodeFirstLoadBalancingPolicy: Adding host xx.xx.xx.134 (datacenter1)
(+25 times "Adding host")
14/12/08 18:55:21 INFO com.datastax.spark.connector.cql.CassandraConnector: Connected to Cassandra cluster: production_cassandra
...
```

Any ideas?

-kr, Gerard.

**Comment by bcantoni** [comment]
Closing because it looks like this discussion concluded.

For any follow-ups, let's move to the user's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
