### ISSUE TITLE
Setting connector's system properties on the executors

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#467]
I'm trying to implement the advice @jacek-lewandowski gave me on this discussion #465, but I'm having some difficult time finding the right way to set a system-wide property like 'spark.cassandra.connection.keep_alive_ms' on the executors.

I think that the spark way would be to use 'spark.executor.extraJavaOptions', like this:
```bash
spark.executor.extraJavaOptions = "-Dspark.cassandra.connection.keep_alive_ms=12000"
```
but it's illegal in Spark to set a property that starts by "-Dspark." [1]

I also tried the following, but without effect:
```bash
spark.executorEnv.spark.cassandra.connection.keep_alive_ms=12000
```
What would be the recommended way to setting these system-wide properties?

(not on the spark-conf file: we run on Mesos and use specific configuration for each job) 

-kr, Gerard.

[1] https://github.com/apache/spark/blob/master/core%2Fsrc%2Fmain%2Fscala%2Forg%2Fapache%2Fspark%2FSparkConf.scala#L269

**Comment by bcantoni** [comment]
Closing because it looks like this discussion concluded.

For any follow-ups, let's move to the user's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
