### ISSUE TITLE
Single partition when using CassandraRDD

### ISSUE THREAD

**Issue by alonpeer** [datastax/spark-cassandra-connector#471]
I'm trying to use the connector in its simplest form. I'm running the following from Spark shell:

    val rdd = sc.cassandraTable(ks, table).where(s"date_time IN ($keys)")
    rdd.count

`keys` is a list of partition keys I'd like to pull. I'm attempting to read ~1000 wide rows.

I have 10 workers in my cluster, and I've set `spark.cassandra.input.split.size` to a very low value (default is 100k, so it makes sense just 1 partition will be created).

When running in debug mode, I see the following line: `CassandraRDD: Created total 1 partitions for ...`.

I'm using release 1.1.0 of the connector.

What might cause this behavior?

**Comment by bcantoni** [comment]
Closing because it looks like this discussion has concluded.

If there are follow-up comments, please discuss on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
