### ISSUE TITLE
getUUID not available for cassandraSql 

### ISSUE THREAD

**Issue by svishnu88** [datastax/spark-cassandra-connector#474]
when i use spark sql , I am not able to get UUID from cassandra . 

If i use getString then it throws a cast exception.

Is there a work around for this.

**Comment by bcantoni** [comment]
This issue has been quiet for a while now, so I will close it out.

If you still need help on this, please raise your question on the Spark Connector User's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
