### ISSUE TITLE
Performance considerations when using the Spark Cassandra Connector

### ISSUE THREAD

**Issue by maasg** [datastax/spark-cassandra-connector#476]
Hi there,

I'm currently working on performance tuning of our Spark Streaming jobs. In the process of understanding where time is spent for each batch, I've noticed that the connector adds few seconds execution time to each batch.

How tested: I removed all `rdd.saveToCassandra` calls and replace them with `.count` to force the rdd computation. With a steady load on the system of about 500 req/s, that specific job takes around 1s `streaming_lastCompletedBatch_processingTime`. Adding back the `rdd.saveToCassandra` call, makes the same metric to go up to 3s  (those are rounded off average times over ~50 batches).

When I check for  the `TableWriter` timing (for each worker), times are on the millisecond range:
(sample)
```bash
14/12/09 16:55:12 INFO TableWriter: Wrote 333 rows in 131 batches to ks.values in 0.072 s.
14/12/09 16:55:12 INFO TableWriter: Wrote 354 rows in 131 batches to ks.values in 0.072 s.
14/12/09 16:55:12 INFO TableWriter: Wrote 379 rows in 131 batches to ks.values in 0.079 s.
14/12/09 16:55:12 INFO TableWriter: Wrote 363 rows in 131 batches to ks.values in 0.080 s.
14/12/09 16:55:12 INFO TableWriter: Wrote 361 rows in 131 batches to ks.values in 0.084 s.
14/12/09 16:55:12 INFO TableWriter: Wrote 346 rows in 131 batches to ks.values in 0.040 s.
```
Those add up for 0.43s seconds. Each workers has a similar load, happening in parallel.

I would like to understand where the rest of the time is going to.   On #465 we had an interesting discussion on connection ttl and I'm currently experimenting with it.  What other elements should be taken into account? How could those be measured?

In Spark Streaming every second counts and we are looking at tuning every element that takes part of that micro-batch processing to maximize our throughput.

Insights on the Connector lifecycle are much appreciated, in particular those involved in each streaming batch.

**Comment by maasg** [comment]
Hi @pkolaczk,  thanks for your message. 

How could I measure this split calculation?  Are any other factors involved in the Spark-Cassandra interaction at each loop outside of the actual prepare statement / insert?

**Comment by pkolaczk** [comment]
The call responsible for this is `CassandraRDD#getPartitions`. I guess Spark calls it once per each RDD. If C* topology doesn't change between those calls, then indeed, it would be a good idea to add some kind of caching to this method.

**Comment by maasg** [comment]
@pkolaczk AFAIK, there's no CassandraRDD in the write path. The work is done by the [TableWriter](https://github.com/datastax/spark-cassandra-connector/blob/master/spark-cassandra-connector%2Fsrc%2Fmain%2Fscala%2Fcom%2Fdatastax%2Fspark%2Fconnector%2Fwriter%2FTableWriter.scala).
What would be the factors involved in that case?

**Comment by pkolaczk** [comment]
Hmm, then I was wrong. I thought you're writing from a CassandraRDD.
Then I don't know any other reasons for it to be slow. It just opens the
connection and writes. Might be worth checking if connection keepalive is
large enough, so it doesn't keep constantly disconnecting and connecting,
and it should be fine.


[image: datastax_logo.png] <http://www.datastax.com/>

PIOTR KOŁACZKOWSKI

Lead Software Engineer, DSE Analytics | pkolaczk@datastax.com

[image: twitter] <https://twitter.com/pkolaczk> [image: facebook.png]
<https://www.facebook.com/datastax> [image: linkedin]
<https://www.linkedin.com/in/pkolaczk> [image: g+.png]
<https://plus.google.com/+Datastax/about>
<http://feeds.feedburner.com/datastax> <https://github.com/datastax/>

2015-01-06 15:01 GMT+01:00 Gerard Maas <notifications@github.com>:

**Comment by maasg** [comment]
In the write path, is there some operation that targets only 1 node in the Cassandra ring?  I'm observing that the streaming job execution time is correlated to one particular node that is clearly hit heavier than the rest. I don't think it's about some particular row that is getting overloaded b/c data is fairly distributed and we have `vnodes` enabled. 
![spark-n-cassandra-bound-processing-time-20140106_115943](https://cloud.githubusercontent.com/assets/874997/5631358/376087c6-95c6-11e4-81e4-1b9251a9fad0.png)

`connection keepalive` improves this, but I want to understand this behavior. It has caused our jobs to crash due as the job gets over its 'batch interval'  threshold.

**Comment by maasg** [comment]
Hi @pkolaczk ,

Thanks a lot for the insights. This TokenAwareLBP sounds like what I need. I actually thought that the current impl was working that way.
 
I'm still puzzled by this node-bound behavior though. We are running Spark on Mesos, separate from Cassandra. Would there still be a `LocalNode` assigned to each Spark executor?

I increased the connection TTL to the same time than the Streaming interval. The job performance dramatically improves, I still see the correlation with 1 node. This could be explained if each executor binds itself to a Cassandra 'coordinator' node. (if that is the case, I'll need to check how Kafka is distributing data at the other side of this pipeline)  

![spark-streaming-vs-cassandra-with-long-connection-ttl](https://cloud.githubusercontent.com/assets/874997/5647128/51306f64-9683-11e4-90f7-db8848f9e73b.png)

**Comment by pkolaczk** [comment]
Every executor node selects the coordinator separately, and it uses a Random.shuffle for nodes at equal distance. So if your C* nodes are not collocated with Spark worker nodes, it should hammer nodes  randomly, and even use different ones between queries. See `com/datastax/spark/connector/cql/LocalNodeFirstLoadBalancingPolicy.scala` for details.

**Comment by maasg** [comment]
@pkolaczk Thanks for the clarification. 
Should I conclude from this that those peaks should be data-related?

**Comment by maasg** [comment]
@pkolaczk  sorry to insist but I'm seeing a clear correlation of Cassandra overload and the Streaming Job while the intake load remains stable. Any clues where to look? 
![weird-overload-streaming-cassandra](https://cloud.githubusercontent.com/assets/874997/5654025/d32ddc36-96bf-11e4-8a48-d59f0acb02d1.png)

**Comment by pkolaczk** [comment]
How many receivers do you have? Are you streaming data into all of your nodes at the same rate or maybe you have one node serving as a data ingestion point? 

@helena do you have any ideas what could cause such an unbalanced load when using Kafka?

**Comment by maasg** [comment]
Hi @pkolaczk @helena just a quick update. 
I got another interesting pattern:
![spark-cassandra-compaction](https://cloud.githubusercontent.com/assets/874997/5667072/1f2a6dd4-9765-11e4-80fc-8c7d4ac0a044.png)
This multi-node stress seems to be on-going compaction  (from looking at the cassandra/system.log)

The single node correlation remains a mystery.

**Comment by helena** [comment]
@maasg I am going to create a ticket for our performance qa team to look into this. 
Thanks for all of the detail. They may have follow up questions for you WRT reproducing your issue.

**Comment by maasg** [comment]
Hi @Helena that sounds good. Thanks. 
BTW, I've summarized my efforts to improve Spark Streaming throughput on a blog post: http://www.virdata.com/tuning-spark/ 
Optimizing the Cassandra write path as well would make the job complete.

**Comment by bcantoni** [comment]
@helena once you have the details captured in a new JIRA, you can close out this one.

**Comment by jacek-lewandowski** [comment]
Moved to JIRA: https://datastax-oss.atlassian.net/browse/SPARKC-51
