### ISSUE TITLE
 Where condition involving multiple partition

### ISSUE THREAD

**Issue by bhardwajrajesh** [datastax/spark-cassandra-connector#503]
Lets consider with key as ((PK1,PK2),Data1)

How to make query with where

(PK1="A" and PK2 in (1,2,3) and data1 > 3 and data1 < 7) or (PK1="B" and PK2 in (3,4,3) and data1 > 1 and data1 < 2)

**Comment by bhardwajrajesh** [comment]
I meant , how to do server side filtering. I see issue #37 
https://github.com/datastax/spark-cassandra-connector/issues/37
Issue #154 
https://github.com/datastax/spark-cassandra-connector/pull/154

Can you please provide comments, if any one of the jira will cover the above scenario. If not , can you please suggest a workaround

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector User's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
