### ISSUE TITLE
Spark task - split on several workers

### ISSUE THREAD

**Issue by eripe970** [datastax/spark-cassandra-connector#508]
Hi, 

I have a Cassandra setup with 5 nodes and 5 workers. I have a Spark job that takes around 5 hours to execute in total on these nodes. 

My problem is that if one of the tasks fail, for example if the cassandra isn't accessible, then I think that the failing task should be split into several minor tasks and executed on each one of the workers that are available. Is such a setup possible? 

Using DSE 4.5.

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector User's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
