### ISSUE TITLE
Spark 1.2 and Scala version 2.11

### ISSUE THREAD

**Issue by rroopreddy** [datastax/spark-cassandra-connector#510]
Now that the code is updated to support Spark 1.2. Is there a plan to generate the Scala 2.11 version of libraries? May you can take an approach similar to Spark where libraries for both Scala 2.10 and 2.11 version can be generated into maven repository.

BTW, When is the next version getting pushed to Repo?

Regards,
Ravi R

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector User's list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
