### ISSUE TITLE
Add support for INSERT INTO with named columns

### ISSUE THREAD

**Issue by bithavoc** [datastax/spark-cassandra-connector#513]
Currently you can do `INSERT INTO table` but it's impossible to do `INSERT INTO table(column1, column2, column3)`.

When you add columns to the destination table, all fields needs to be appended at the end of the SELECT where with named columns the order does not matter.

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC
