### ISSUE TITLE
Scheduler distribute several tasks to same executor

### ISSUE THREAD

**Issue by eripe970** [datastax/spark-cassandra-connector#516]
Hi, 

I'm trying to run a spark job on a cluster with 5 executors. The spark job takes around 6h to complete on each executor. The problem that I'm facing is that some of the workers/executors are registered to the job late. This means that the works is divided up into 5 different parts but 3 of them are assigned to the same executor. 

I can from the log see messages like below after the Scheduler has distributed the tasks to the available executors. 

- org.apache.spark.scheduler.cluster.SparkDeploySchedulerBackend: Registered executor: Actor[akka.tcp://sparkExecutor@ip:59367/user/Executor#-218397229] with ID 0

Any suggestions for how this can be fixed so that the job doesn't start before all workers have been registered? All nodes are registered at available all the time in the Spark Web UI. Not really sure if this is a issue related to the spark-cassandra-connector but other things seems to be working fine. 

Using DSE 4.5. 

/Erik

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC
