### ISSUE TITLE
NullPointerException: Cannot start embedded cassandra

### ISSUE THREAD

**Issue by elmalto** [datastax/spark-cassandra-connector#519]
I am writing my unit tests and try to start an embedded cassandra server:

```
abstract class GraphSpec extends WordSpec with MustMatchers with OptionValues with BeforeAndAfter with SharedEmbeddedCassandra

trait SharedEmbeddedCassandra extends EmbeddedCassandra {
  def clearCache(): Unit = CassandraConnector.evictCache()
}

class GraphTest extends GraphSpec {
  useCassandraConfig("cassandra.yaml")
...
}
```

and I always get: 

```
java.lang.NullPointerException at
com.datastax.spark.connector.embedded.EmbeddedIO$class.closeAfterUse(Embedded.scala:26)
```

cassandra.yaml lies in my test/resources/cassandra.yaml but I tried various other locations including main resources

I run the test with sbt run

**Comment by bcantoni** [comment]
This project has migrated away from GitHub Issues.

Please raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC
