### ISSUE TITLE
assertion failed: Missing columns needed

### ISSUE THREAD

**Issue by MichaelHirn** [datastax/spark-cassandra-connector#524]
We have a case class - lets call it `Order` - and we load some data from C* like this:
```
sc.cassandraTable[Order](keyspace, "orders").select("a", "b", "c").toArray
```
Which raises the above error, because the case class `Order` has two more var elements d and e, which are not present in the cassandra table. The case class looks something like this.

```
case class Order(a: String, b: String, c: String) {
  var d = "some_default"
  def setD = ...

  var e = "some_default"
  def setE = ...
}
```

This is the complete error with some backtrace
```
Caused by: java.lang.AssertionError: assertion failed: Missing columns needed by Order: d, e
at scala.Predef$.assert(Predef.scala:179)                            
at com.datastax.spark.connector.rdd.CassandraRDD.verify$lzycompute(CassandraRDD.scala:271)
at com.datastax.spark.connector.rdd.CassandraRDD.verify(CassandraRDD.scala:263)
at com.datastax.spark.connector.rdd.CassandraRDD.getPartitions(CassandraRDD.scala:292)
```

How should i work around this and why does the cassandra library force me to select d and e - which is not needed to initiate the case class properly as far as i'm concerned?

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Instead, you can raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC
