### ISSUE TITLE
attempting to use spark-cassandra-connector with pyspark results in "AttributeError: 'SparkContext' object has no attribute 'cassandraTable'"

### ISSUE THREAD

**Issue by spaceshipoperator** [datastax/spark-cassandra-connector#526]
please provide a working example of using the spark-cassandra-connector with pyspark

the following gist documents my attempt and results

https://gist.github.com/spaceshipoperator/135b422335d4ba86868c

if there is not enough information, please let me know specifically what else I might provide.

**Comment by bcantoni** [comment]
Currently, PySpark only works with Cassandra when using DataStax Enterprise ([docs](http://www.datastax.com/documentation/datastax_enterprise/4.6/datastax_enterprise/spark/sparkPySpark.html)).

For any follow-ups, you can raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

(This project is migrating away from GitHub Issues.)
