### ISSUE TITLE
java.io.IOException: Exception during execution of SELECT query 

### ISSUE THREAD

**Issue by wajdiawwad** [datastax/spark-cassandra-connector#528]
Hi,
i have spark-1.1.0 on server A with spark-cassandra-connector_2.10-1.1.1, and Cassandra 2.1.0 on server B, which is in the same datacenter  as server A,

i have big table and im trying to load it on cache so i can run some analytics over it by the following way
sc.cassandraTable("myKeyspace", "myTable").select("feedid","action").cache() 

the job take more than 30 minutes or less then i use to get 

15/01/29 13:06:07 WARN TaskSetManager: Lost task 0.0 in stage 12.0 (TID 19, 100.82.210.52): java.io.IOException: Exception during execution of SELECT "action", "feedid" FROM "myKeyspace"."myTable" WHERE token("id") > ? AND token("id") <= ? AND  feedid = ?  ALLOW FILTERING: All host(s) tried for query failed (tried: /MY_IP:9042 (com.datastax.driver.core.exceptions.DriverException: Timed out waiting for server response))
        com.datastax.spark.connector.rdd.CassandraRDD.com$datastax$spark$connector$rdd$CassandraRDD$$fetchTokenRange(CassandraRDD.scala:349)
        com.datastax.spark.connector.rdd.CassandraRDD$$anonfun$13.apply(CassandraRDD.scala:362)
        com.datastax.spark.connector.rdd.CassandraRDD$$anonfun$13.apply(CassandraRDD.scala:362)
        scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        com.datastax.spark.connector.util.CountingIterator.hasNext(CountingIterator.scala:10)
        org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:235)
        org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:163)
        org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:70)
        org.apache.spark.rdd.RDD.iterator(RDD.scala:227)
        org.apache.spark.rdd.FilteredRDD.compute(FilteredRDD.scala:34)
        org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
        org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
        org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
        org.apache.spark.scheduler.Task.run(Task.scala:54)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:177)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        java.lang.Thread.run(Thread.java:745)

 P.S i already increase the read.timeout_ms in spark , also *_request_timeout_in_ms in Cassandra,  but i still getting same error

any suggestion how to make it work ?

Thanks in advance.

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Instead, you can raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If a new bug or feature needs to be captured, please write up in the new Spark Connector JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC
