### ISSUE TITLE
Upgrade metrics to 3.1

### ISSUE THREAD

**Issue by analytically** [datastax/spark-cassandra-connector#529]
Fully compatible, just the changes the maven package name.

io.dropwizard.metrics

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Discussions have moved to the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

New bugs or features are being captured and managed here:
https://datastax-oss.atlassian.net/browse/SPARKC
