### ISSUE TITLE
Failed to open native connection to Cassandra

### ISSUE THREAD

**Issue by sumant28** [datastax/spark-cassandra-connector#530]
Hi,

I am trying to connect to cassandra from spark-jobserver by creating spark context.
I have included libraries of spark-cassandra-connector in spark-jobserver. But when I am trying to connect to cassandra I am getting below error : 

***********************************************************************************************************
    "errorClass": "java.io.IOException",
    "cause": "All host(s) tried for query failed (tried: /XX.XXX.XX.XXX:9042 (com.datastax.driver.core.TransportException: [/XX.XXX.XX.XXX:9042] Cannot connect))",

    "causingClass": "com.datastax.driver.core.exceptions.NoHostAvailableException",
    "message": "Failed to open native connection to Cassandra at {XX.XXX.XX.XXX}:9042"
***********************************************************************************************************

sbt conf file where I have included the spark-cassandra-connector library

libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector" % "1.1.0",
libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector-java" % "1.1.0",
libraryDependencies += "org.apache.cassandra" % "cassandra-thrift" % "2.1.2",
libraryDependencies += "org.apache.cassandra" % "cassandra-clientutil" % "2.1.2",
libraryDependencies += "com.datastax.cassandra" % "cassandra-driver-core" % "2.1.3",

***********************************************************************************************************

Spark Code : 

    val conf = new SparkConf(true)
   .set("spark.cassandra.connection.host", "127.0.0.1")
    val sc = new SparkContext("spark://127.0.0.1:7077", "test", conf)

  val rdd = sc.cassandraTable("test", "kv")
  println(rdd.count)

***********************************************************************************************************

cassandra.yaml file properties :

ssl_storage_port: 7001
listen_address: localhost
start_native_transport: true
native_transport_port: 9042
start_rpc: true
rpc_address: localhost
rpc_port: 9160
rpc_keepalive: true

***********************************************************************************************************

Could someone guide me how to solve this issue or any possible causes ?

Thanks in advance.
-Sumant

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Discussions have moved to the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

New bugs or features are being captured and managed here:
https://datastax-oss.atlassian.net/browse/SPARKC

**Comment by marceau06** [comment]
Try adding the port on your configuration

`.set("spark.cassandra.connection.port", "9042")`

You can try to use socat command to forward your local port to your remote port:

socat tcp-listen:9042,fork tcp:localhost:9042 &
