### ISSUE TITLE
NullPointerError when using a CassandraRDD within a foreach call

### ISSUE THREAD

**Issue by calebskidmore** [datastax/spark-cassandra-connector#532]
I am not sure if I am taking the right approach here, so any suggestions would be appreciated.  For each line in a file, I need to query Cassandra.  When I pass the CassandraRDD into my method, it results a NullPointerException.  It appears to me that the CassandraRDD is not functioning correctly once it has been deserialized.

The calling method is as follows:

  def processRDD(fileRdd: RDD[(Long, String)], table:CassandraRDD[CassandraRow]): Unit = {
    fileRdd.foreach(processMesages(_, table))
  }

The method that throws the error is as follows:

def processMesages(s: Tuple2[Long, String], table:CassandraRDD[CassandraRow]): String = { 
   val query = table.select("id").where("id = ?", s._2)
    println(query.count)
    s._2
}

The error I receive is as follows:

java.lang.NullPointerException:
        org.apache.spark.rdd.RDD.<init>(RDD.scala:125)
        com.datastax.spark.connector.rdd.CassandraRDD.<init>(CassandraRDD.scala:48)
        com.datastax.spark.connector.rdd.CassandraRDD.copy(CassandraRDD.scala:82)
        com.datastax.spark.connector.rdd.CassandraRDD.select(CassandraRDD.scala:130)

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Discussions have moved to the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
