### ISSUE TITLE
WordCountDemo hangs on RDD.collect()

### ISSUE THREAD

**Issue by tulinski** [datastax/spark-cassandra-connector#534]
Hi,

I've been trying to run a WordCountDemo example from your repo (spark-cassandra-connector-demos/simple-demos/.../scala), but it hangs on RDD.collect() statement. Before that saveToCassandra("demo", "wordcount") method inserts data into the local cassandra cluster (ccm / Cassandra 2.1.2 / 5 nodes) correctly.

Dependencies in my project:
scalaVersion := "2.10.4"

libraryDependencies ++= Seq(
  "com.datastax.spark" % "spark-cassandra-connector_2.10" % "1.1.1",
  "org.apache.spark" % "spark-core_2.10" % "1.1.1",
  "org.apache.spark" % "spark-streaming_2.10" % "1.1.1",
  "org.apache.spark" % "spark-sql_2.10" % "1.1.1"
)

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Discussions have moved to the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
