### ISSUE TITLE
java.util.NoSuchElementException: key not found: UserDefinedType

### ISSUE THREAD

**Issue by instagrille** [datastax/spark-cassandra-connector#538]
Cassandra table: comment (use UserDefinedType)

Scala code:
    val cc = new CassandraSQLContext(sc)
    cc.setKeyspace("xxx")
    val result = cc.cassandraSql("SELECT * FROM comment limit 1")

Throw exception:
java.util.NoSuchElementException: key not found: UserDefinedType

**Comment by alexliu68** [comment]
which version of Spark Cassandra Connector do you use?

**Comment by alexliu68** [comment]
Master branch test on UDT table works as https://github.com/datastax/spark-cassandra-connector/blob/master/spark-cassandra-connector/src/it/scala/com/datastax/spark/connector/sql/CassandraSQLSpec.scala#L281

**Comment by instagrille** [comment]
lib version:
- apache-cassandra-2.1.0.jar
- spark-assembly-1.2.0-hadoop2.4.0.jar
- spark-cassandra-connector-assembly-1.2.0-SNAPSHOT.jar

**Comment by jacek-lewandowski** [comment]
We are sorry, but we are going to disable GitHub tracker. 

If you have problems and you are looking for help, please use a forum at: https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If you want to report bugs, improvement or feature requests, please use JIRA at:
https://datastax-oss.atlassian.net/browse/

Please move your questions to the new location.

Thanks
