### ISSUE TITLE
java.lang.ClassNotFoundException 1.2.0-alpha1 + DSE 4.6

### ISSUE THREAD

**Issue by sathibault** [datastax/spark-cassandra-connector#539]
DSE 4.6 = Cassandra 2.0.11 & Spark 1.1.0

java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/planning/GenericStrategy
        at org.apache.spark.sql.cassandra.CassandraSQLContext$$anon$1.<init>(CassandraSQLContext.scala:66)
...
Caused by: java.lang.ClassNotFoundException: Class org.apache.spark.sql.catalyst.planning.GenericStrategy not found in modules [ModuleClassLoader:Analytics, SystemClassLoader]
       at com.datastax.bdp.loader.SystemClassLoader.loadClass(SystemClassLoader.java:120)
..

**Comment by alexliu68** [comment]
Can you tell more detail how to reproduce this bug, It looks like DSE customized class loader configuration issue.

**Comment by alexliu68** [comment]
BTW, you can open a jira ticket to track this issue https://datastax-oss.atlassian.net/
We no longer use github to track issue.

**Comment by sathibault** [comment]
This exception occurs during start up of spark-shell.  Specifically, I used dse spark-classpath to get a classpath, substituted the the two alpha1 connector jars for the packaged ones, and started spark-shell directly.

**Comment by jacek-lewandowski** [comment]
We are sorry, but we are going to disable GitHub tracker. 

If you have problems and you are looking for help, please use a forum at: https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

If you want to report bugs, improvement or feature requests, please use JIRA at:
https://datastax-oss.atlassian.net/browse/

Please move your questions to the new location.

Thanks
