### ISSUE TITLE
what should I do if my cassandra table contains dot('.') in field name?

### ISSUE THREAD

**Issue by LishuLiu** [datastax/spark-cassandra-connector#540]
My schema look like below:
scala> task_trace.printSchema()
root
 |-- received_datetime: long (nullable = true)
 |-- task_body: struct (nullable = true)
 |    |-- cerberus_id: string (nullable = true)
 |    |-- sm.result: struct (nullable = true)
 |    |    |-- code: string (nullable = true)
 |    |    |-- created: string (nullable = true)
 |    |    |-- description: string (nullable = true)
 |-- task_id: string (nullable = true)

How can I access the fields in sm.result? 
I tried 
scala> val res = cc.sql("SELECT received_datetime, task_body.cerberus_id, task_body.sm.result.description FROM task_trace WHERE task_id = 'fff7304e-9984-4b45-b10c-0423a96745ce'")
But it tries to find sm instead:
java.lang.RuntimeException: No such struct field sm in cerberus_id, created, description, sm.result, task_id.

**Comment by bcantoni** [comment]
Looks like this conversation already happened on the user list, and resulted in a bug written against Spark:
https://issues.apache.org/jira/browse/SPARK-5632
