### ISSUE TITLE
com.datastax.driver.core.exceptions.InvalidTypeException

### ISSUE THREAD

**Issue by justinjoseph89** [datastax/spark-cassandra-connector#543]
Hi,
I am using spark-cassandra-connector. it worked well for me, but today when i tried to run with another table from cassandra it giving me an error
com.datastax.driver.core.exceptions.InvalidTypeException: Invalid 32-bits integer value, expecting 4 bytes but got 0.

My code is follows,
JavaRDD<News> rdd = functions.cassandraTable("emsSdk",
                "activity_log").map(new Function<CassandraRow, News>() {
            @Override
            public News call(CassandraRow line) {
                News rdd = new News();
                rdd.setName(line.getAny("uid").toString());
                rdd.setPayload(line.getAny("activity_desc").toString());
                rdd.setId(line.getAny("key").toString());
                return rdd;
            }
});

Where News is my bean class and activity_log is my table name. Is there any mistakes in my code? Or is there any difference between CQL versions?

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Instead, you can raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user
