### ISSUE TITLE
Version Compatibility table in README is wrong

### ISSUE THREAD

**Issue by bobbyrauchenberg** [datastax/spark-cassandra-connector#544]
Hi 

Probably a small thing, but the Version Compatibility in your README is completely broken :)

I've just been trying to use the spark-cassandra-connector with spark v1.0.1 which it claims is supported, but it blows up trying to call a method that doesn't exist in `TaskContext` for spark v1.0.1

```java.lang.NoSuchMethodError 
(java.lang.NoSuchMethodError: org.apache.spark.TaskContext.addTaskCompletionListener
(Lscala/Function1;)Lorg/apache/spark/TaskContext;}
com.datastax.spark.connector.rdd.CassandraRDD.compute(CassandraRDD.scala:399)
org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
org.apache.spark.rdd.RDD.iterator(RDD.scala:229)```

**Comment by bcantoni** [comment]
This project is migrating away from GitHub Issues.

Instead, could you please can raise your question on the Spark Connector Users' list here:
https://groups.google.com/a/lists.datastax.com/forum/#!forum/spark-connector-user

For your example, can you also include which version of the connector you are using?
