### ISSUE TITLE
Add a method to pass a limit clause to a CQL query

### ISSUE THREAD

**Issue by vsubrama001** [datastax/spark-cassandra-connector#78]
How do you Limit the number of rows returned from Cassandra to a RDD ? Is the 'Limit'operation supported like in the query below

select date, data_source_type_code,state_name, is_alarm, state_timestamp from wfm_rta.employee_status_and_alarm_detail where state_timestamp> '2014-07-19 19:45:25-0700' limit 100 ALLOW FILTERING

**Comment by bcantoni** [comment]
I moved this to JIRA:
https://datastax-oss.atlassian.net/browse/SPARKC-31
